format = """
$shlvl\
$shell\
$env_var\
$username\
[@](green)\
$hostname\
:\
$directory\
$git_branch\
$git_status\
$fill\
$all\
$status\
$cmd_duration\
$line_break\
$character\
"""

continuation_prompt = '[> ](grey)'

[character]
format = "$symbol "
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green italic'

[username]
disabled = false
show_always = true
style_user = "bold green"
style_root = "bold yellow"
format = "[$user]($style)"

[hostname]
disabled = false
ssh_only = false
style="bold green"
format = "[$hostname]($style)"

[directory]
disabled = false
truncate_to_repo = false
truncation_length = 0
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style)'

[fill]
disabled = false
style = "white"

[cmd_duration]
format = "[$duration](yellow) "

[git_branch]
format = " [$symbol $branch]($style)"
symbol = ""
style = "bold yellow"

[git_status]
format = '( [$all_status$ahead_behind]($style))'
style = "yellow"

[status]
disabled = false
format = "[$status]($style) "

[gcloud]
disabled = true

[nodejs]
symbol = ""
[c]
symbol = " "
[rust]
symbol = ""
[golang]
symbol = ""
[php]
symbol = ""
[java]
symbol = " "
[kotlin]
symbol = ""
[haskell]
symbol = ""
[python]
symbol = ""
python_binary = ['python3', 'python']
